Repository bcgov/smk-firewood, pull requests merged in 2022-03, with the labels that each got.

#13 SMK updated to 1.0.9
  package-lock.json
  package.json
Labels: 20220302-1617

#17 Update about panel
  smk-config.json
Labels: 20220318-2345

#19 Fix title
  index.html
Labels: 20220322-2015
